name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
  - title: "Features"
    labels:
      - feature
      - enhancement
  - title: "Bug Fixes"
    labels:
      - bug
  - title: "Maintenance"
    labels:
      - chore
      - refactor
change-template: "- $TITLE (#$NUMBER)"
template: |
  ## Changes
  $CHANGES

  **Full Changelog:** $COMPARE_URL
