site_name: Heavens Above Documentation
site_url: https://fmanahil446-droid.github.io/heavens-above/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - codehilite
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fmanahil446-droid/heavens-above
