site_name: Heavens Above Documentation
site_url: https://fmanahil446-droid.github.io/heavens-above/
theme:
  name: material
  features:
    - navigation.expand
    - navigation.instant
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.suggest

plugins:
  - search
  - awesome-pages
  - minify:
      minify_html: true
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - fenced_code
  - admonition
  - codehilite
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/<your-username>/<your-repo-name>

nav:   # 👈 Optional — keep only if you want a custom homepage label
  - Home: index.md
