name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing project dependencies..."
          npm install || echo "Dependency installation failed!"

      - name: Run lint check
        run: |
          echo "Running lint check..."
          npm run lint && echo "Linting passed successfully!" || echo "Linting failed!"

      - name: Run tests
        run: |
          echo "Running test cases..."
          npm test && echo "All tests passed successfully!" || echo "Some tests failed!"

      - name: Final status
        run: echo "Continuous Integration workflow completed!"
