name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1"  
  workflow_dispatch:      

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20     

      - name: Install dependencies
        run: npm install

      - name: Check for outdated dependencies
        run: |
          echo "Checking for outdated npm dependencies..."
          npm outdated || true

      - name: Update dependencies
        run: |
          echo "Updating dependencies..."
          npm update

      # Add this new section here
      - name: Run npm audit fix
        run: npm audit fix || true

      # Then add this section to commit and push updates
      - name: Commit and push updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package*.json
          git commit -m "Auto dependency update" || echo "No changes to commit"
          git push

      # Optional: Run tests to ensure updates don't break anything
      - name: Run tests
        run: |
          echo "Running tests..."
          npm test || echo "Tests failed – please check compatibility."

      - name: Log update completion
        run: echo "Dependency update workflow completed successfully."
