name: Dependency Updates

on:
  schedule:
    - cron: "0 0 * * 1"   
  workflow_dispatch:        

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check for outdated dependencies
        run: |
          echo "Checking for outdated npm dependencies..."
          npm outdated || true

      - name: Update dependencies
        run: |
          echo "Updating dependencies..."
          npm update

      - name: Run npm audit fix
        run: npm audit fix || true

      - name: Commit updated dependencies
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b dependency-updates-$(date +%Y-%m-%d)
          git add -f package*.json
          git commit -m "Auto dependency update on $(date +%Y-%m-%d)" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated Dependency Update"
          body: "This pull request includes automatically updated dependencies. Please review before merging."
          branch: dependency-updates
          base: main
          commit-message: "chore: automated dependency updates"
          labels: dependencies, automation

      - name: Run tests
        run: |
          echo "Running tests..."
          npm test || echo "Tests failed – please check compatibility."

      - name: Log update completion
        run: echo "Dependency update workflow completed successfully."
