name: Deployment Pipeline

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run tests
      - name: Run tests
        run: npm test

      # Step 5: Deploy to Railway
      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          railwayToken: ${{ secrets.RAILWAY_API_KEY }}
          environment: "production"

      # Step 6: Success message
      - name: Success message
        if: ${{ success() }}
        run: echo "✅ Deployment to Railway completed successfully!"
